=== Ps1k0/examenDDL/xsd.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">




               <xsd:element name="Examen" type="texamen1"/>
                    <xsd:complexType name="texamen1">
                         <xsd:sequence>


                              <xsd:element name="Aspirantes" type="tipoaspirante" maxOccurs="unbounded"/>
                              <xsd:element name="Meritos" type="tipomeritos" maxOccurs="unbounded"/>
                              <xsd:element name="Convalidacion_grados" type="tipoconvalidacion_grados" maxOccurs="unbounded"/>
                              <xsd:element name="Requisitos_aspirante" type="tiporequisitos_aspirante" maxOccurs="unbounded"/>
                              <xsd:element name="Dispensa_medica" type="tipoDispensa_medica" maxOccurs="unbounded"/>
                              <xsd:element name="Jueces" type="tipojueces" maxOccurs="unbounded"/>
                              <xsd:element name="Criterio_valoracion" type="tipocriterio_valoracion" maxOccurs="unbounded"/>
                              <xsd:element name="Tribunal" type="tipotribunal" maxOccurs="unbounded"/>
                              <xsd:element name="Abonar_cuota" type="tipoabonar_cuota" maxOccurs="unbounded"/>
                              <xsd:element name="Suspender_examen" type="tiposuspender_examen" maxOccurs="unbounded"/>
                              <xsd:element name="Quintodanysuperior" type="tipoquintodanysuperior" maxOccurs="unbounded"/>
                              <xsd:element name="Hasta3erdan" type="tipohasta3erdan" maxOccurs="unbounded"/>
                              <xsd:element name="Cinturonnegro" type="tipocinturonnegro" maxOccurs="unbounded"/>
                              <xsd:element name="Cinturonnegroprimerdan" type="tipocinturonnegroprimerdan" maxOccurs="unbounded"/>
                              <xsd:element name="Cinturonnegrosegundodan" type="tipocinturonnegrosegundodan" maxOccurs="unbounded"/>
                              <xsd:element name="Cinturonnegrotercerdan" type="tipocinturonnegrotercerdan" maxOccurs="unbounded"/>
                              <xsd:element name="Cinturonnegrocuartodan" type="tipocinturonnegrocuartodan" maxOccurs="unbounded"/>
                              <xsd:element name="Resultados" type="tiporesultados" maxOccurs="unbounded"/>


                         </xsd:sequence>
                    </xsd:complexType>
               
               



                    <xsd:complexType name="tipoaspirante">
                         <xsd:sequence>
                              <xsd:element name="Id_Aspirantes" type="xsd:integer"/>
                              <xsd:element name="Nombres" type="xsd:string"/>
                              <xsd:element name="Apellidos" type="xsd:string"/>
                              <xsd:element name="DNI" type="xsd:string"/>
                              <xsd:element name="Telefono" type="xsd:string"/>
                              <xsd:element name="Direccion" type="xsd:string"/>
                              <xsd:element name="Fecha_nacimiento" type="xsd:integer"/>
                              <xsd:element name="Dan" type="xsd:string"/>
                              <xsd:element name="Cinturon" type="xsd:string"/>
                              <xsd:element name="Fecha_Ingreso" type="xsd:string"/>
                              <xsd:element name="Foto_Aspirante" type="xsd:string"/>
                              <xsd:element name="Tiempo_Dan_Anterior" type="xsd:integer"/>
                              <xsd:element name="FotoDNI" type="xsd:string"/>
                              <xsd:element name="FotoCarnetGrados" type="xsd:string"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipomeritos">
                         <xsd:sequence>
                              <xsd:element name="Id_Aspirantes" type="xsd:integer"/>
                              <xsd:element name="Edad_aspirante" type="xsd:integer"/>
                              <xsd:element name="LicenciaActualizada" type="xsd:boolean"/>
                              <xsd:element name="TrabajoEscrito" type="xsd:boolean"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipoconvalidacion_grados">
                         <xsd:sequence>
                              <xsd:element name="Id_Aspirantes" type="xsd:integer"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tiporequisitos_aspirante">
                         <xsd:sequence>
                              <xsd:element name="SolicitudhHasta3Dan" type="xsd:boolean"/>
                              <xsd:element name="DanySuperiorCurriculum4" type="xsd:boolean"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipoDispensa_medica">
                         <xsd:sequence>
                              <xsd:element name="Id_Aspirante" type="xsd:integer"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipojueces">
                         <xsd:sequence>
                              <xsd:element name="Id_Jueces" type="xsd:integer"/>
                              <xsd:element name="Nombres" type="xsd:string"/>
                              <xsd:element name="Apellidos" type="xsd:string"/>
                              <xsd:element name="DiplomaJuez" type="xsd:boolean"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipocriterio_valoracion">
                         <xsd:sequence>
                              <xsd:element name="Indumentaria" type="xsd:integer"/>
                              <xsd:element name="AseoPersonal" type="xsd:integer"/>
                              <xsd:element name="EjecuciÃ³nTecnica" type="xsd:integer"/>
                              <xsd:element name="Valores" type="xsd:integer"/>
                              <xsd:element name="Respuestas" type="xsd:integer"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipotribunal">
                         <xsd:sequence>
                              <xsd:element name="Numero_Jueces" type="xsd:integer"/>
                              <xsd:element name="Calificacion_final" type="xsd:integer"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipoabonar_cuota">
                         <xsd:sequence>
                              <xsd:element name="Id_Aspirante" type="xsd:integer"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tiposuspender_examen">
                         <xsd:sequence>
                              <xsd:element name="Id_Aspirante" type="xsd:integer"/>
                              <xsd:element name="SuspenderParcial" type="xsd:boolean"/>
                              <xsd:element name="SuspenderTotal" type="xsd:boolean"/>
                              <xsd:element name="SuspenderSegundaFase" type="xsd:boolean"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipoquintodanysuperior">
                         <xsd:sequence>
                              <xsd:element name="Kata" type="xsd:string"/>
                              <xsd:element name="Coloquio" type="xsd:string"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipohasta3erdan">
                         <xsd:sequence>
                              <xsd:element name="Tecnicas" type="xsd:string"/>
                              <xsd:element name="Kata" type="xsd:string"/>
                              <xsd:element name="Kumite" type="xsd:string"/>
                              <xsd:element name="Campeonatos" type="xsd:string"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipocinturonnegro">
                         <xsd:sequence>
                              <xsd:element name="Tecnica_Directa" type="xsd:string"/>
                              <xsd:element name="Tecnica_Circulares" type="xsd:string"/>
                              <xsd:element name="Tecnica_Pierna" type="xsd:string"/>
                              <xsd:element name="Teoria" type="xsd:string"/>
                              <xsd:element name="Kata" type="xsd:string"/>
                              <xsd:element name="Kumite" type="xsd:string"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipocinturonnegroprimerdan">
                         <xsd:sequence>
                              <xsd:element name="Tecnica_Defensa" type="xsd:string"/>
                              <xsd:element name="Tecnica_Pierna" type="xsd:string"/>
                              <xsd:element name="Tecnica_DirectaIndirecta" type="xsd:string"/>
                              <xsd:element name="Tecnica_Combinada" type="xsd:string"/>
                              <xsd:element name="Teoria" type="xsd:string"/>
                              <xsd:element name="Kata" type="xsd:string"/>
                              <xsd:element name="Kumite" type="xsd:string"/>
                              <xsd:element name="Aplicacion_Tecnica" type="xsd:string"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipocinturonnegrosegundodan">
                         <xsd:sequence>
                              <xsd:element name="Tecnica_Base" type="xsd:string"/>
                              <xsd:element name="Tecnica_Directa" type="xsd:string"/>
                              <xsd:element name="Tecnica_IndirectaCircular" type="xsd:string"/>
                              <xsd:element name="Tecnica_Pierna" type="xsd:string"/>
                              <xsd:element name="Tecnica_Combinada" type="xsd:string"/>
                              <xsd:element name="Teoria" type="xsd:string"/>
                              <xsd:element name="Kata" type="xsd:string"/>
                              <xsd:element name="Kumite" type="xsd:string"/>
                              <xsd:element name="Campeonatos" type="xsd:string"/>
                              <xsd:element name="Tecnicas" type="xsd:string"/>
                              <xsd:element name="Aplicacion_Tecnica" type="xsd:string"/>
                              <xsd:element name="Demo_Libre" type="xsd:string"/>
                         </xsd:sequence>
                    </xsd:complexType>
                    <xsd:complexType name="tipocinturonnegrotercerdan">
                         <xsd:sequence>
                              <xsd:element name="Variaciones_Tecnica" type="xsd:string"/>
                              <xsd:element name="Kumite" type="xsd:string"/>
                              <xsd:element name="Kata" type="xsd:string"/>
                              <xsd:element name="Aplicacion_Tecnica" type="xsd:string"/>
                              <xsd:element name="Teoria" type="xsd:string"/>
                              <xsd:element name="Kumite" type="xsd:string"/>
                              <xsd:element name="Campeonatos" type="xsd:string"/>
                              <xsd:element name="Tecnica" type="xsd:string"/>
                              <xsd:element name="Aplicaciones" type="xsd:string"/>
                              <xsd:element name="Aplicacion_Tecnica" type="xsd:string"/>
                              <xsd:element name="Demo_Libre" type="xsd:string"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    <xsd:complexType name="tipocinturonnegrocuartodan">
                         <xsd:sequence>
                              <xsd:element name="Kumite" type="xsd:string"/>
                              <xsd:element name="Kata" type="xsd:string"/>
                              <xsd:element name="Aplicacion_Tecnica" type="xsd:string"/>
                              <xsd:element name="Teoria" type="xsd:string"/>
                              <xsd:element name="Demo_Libre" type="xsd:string"/>
                         </xsd:sequence>
                    </xsd:complexType>

                    
                    <xsd:complexType name="tiporesultados">
                         <xsd:sequence>
                              <xsd:element name="Id_Aspirante" type="xsd:integer"/>
                         </xsd:sequence>
                    </xsd:complexType>
              
</xsd:schema>

=== Ps1k0/examenDDL/xsd.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="estilo.css"?>
<Examen xmlns:xsi="http/www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">


    <Aspirantes>
        <Id_Aspirantes> </Id_Aspirantes>
        <Nombres></Nombres>
        <Apellidos></Apellidos>
        <DNI></DNI>
        <Teléfono></Teléfono>
        <Direccion></Direccion>
        <Fecha_nacimiento></Fecha_nacimiento>
        <Dan></Dan>
        <Cinturon></Cinturon>
        <Fecha_Ingreso></Fecha_Ingreso>
        <Foto_Aspirante></Foto_Aspirante>
        <Tiempo_Dan_Anterior></Tiempo_Dan_Anterior>
        <FotoDNI></FotoDNI>
        <FotoCarnetGrados></FotoCarnetGrados>
    </Aspirantes>




    <Meritos>
        <Id_Aspirantes></Id_Aspirantes>
        <Edad_aspirante></Edad_aspirante>
        <LicenciaActualizada></LicenciaActualizada>
        <TrabajoEscrito></TrabajoEscrito>
    </Meritos>



    <Convalidacion_grados>
        <Id_Aspirantes></Id_Aspirantes>
    </Convalidacion_grados>



    <Requisitos_aspirante>
        <SolicitudhHasta3Dan></SolicitudhHasta3Dan>
        <DanySuperiorCurriculum4></DanySuperiorCurriculum4>
    </Requisitos_aspirante>



    <Dispensa_medica>
        <Id_Aspirante></Id_Aspirante>
    </Dispensa_medica>


    <Jueces>
        <Id_Jueces></Id_Jueces>
        <Nombres></Nombres>
        <Apellidos></Apellidos>
        <DiplomaJuez></DiplomaJuez>
    </Jueces>

    

    <Criterio_valoracion>
        <Indumentaria></Indumentaria>
        <AseoPersonal></AseoPersonal>
        <EjecuciónTecnica></EjecuciónTecnica>
        <Valores></Valores>
        <Respuestas></Respuestas>
    </Criterio_valoracion>



    <Tribunal>
        <Numero_Jueces></Numero_Jueces>
        <Calificacion_final></Calificacion_final>
    </Tribunal>



    <Abonar_cuota>
        <Id_Aspirante></Id_Aspirante>
    </Abonar_cuota>



    <Suspender_examen>
        <Id_Aspirante></Id_Aspirante>
        <SuspenderParcial></SuspenderParcial>
        <SuspenderTotal></SuspenderTotal>
        <SuspenderSegundaFase></SuspenderSegundaFase>
    </Suspender_examen>



    <Quintodanysuperior>
        <Kata></Kata>
        <Coloquio></Coloquio>
    </Quintodanysuperior>



    <Hasta3erdan>
        <Tecnicas></Tecnicas>
        <Kata></Kata>
        <Kumite></Kumite>
        <Campeonatos></Campeonatos>
    </Hasta3erdan>



    <Cinturonnegro>
        <Tecnica_Directa></Tecnica_Directa>
        <Tecnica_Circulares></Tecnica_Circulares>
        <Tecnica_Pierna></Tecnica_Pierna>
        <Teoria></Teoria>
        <Kata></Kata>
        <Kumite></Kumite>
    </Cinturonnegro>



    <Cinturonnegroprimerdan>
        <Tecnica_Defensa></Tecnica_Defensa>
        <Tecnica_Pierna></Tecnica_Pierna>
        <Tecnica_DirectaIndirecta></Tecnica_DirectaIndirecta>
        <Tecnica_Combinada></Tecnica_Combinada>
        <Teoria></Teoria>
        <Kata></Kata>
        <Kumite></Kumite>
        <Aplicacion_Tecnica></Aplicacion_Tecnica>
    </Cinturonnegroprimerdan>



    <Cinturonnegrosegundodan>
        <Tecnica_Base></Tecnica_Base>
        <Tecnica_Directa></Tecnica_Directa>
        <Tecnica_IndirectaCircular></Tecnica_IndirectaCircular>
        <Tecnica_Pierna></Tecnica_Pierna>
        <Tecnica_Combinada></Tecnica_Combinada>
        <Teoria></Teoria>
        <Kata></Kata>
        <Kumite></Kumite>
        <Campeonatos></Campeonatos>
        <Tecnicas></Tecnicas>
        <Aplicacion_Tecnica></Aplicacion_Tecnica>
        <Demo_Libre></Demo_Libre>
    </Cinturonnegrosegundodan>



    <Cinturonnegrotercerdan>
        <Variaciones_Tecnica></Variaciones_Tecnica>
        <Kumite></Kumite>
        <Kata></Kata>
        <Aplicacion_Tecnica></Aplicacion_Tecnica>
        <Teoria></Teoria>
        <Kumite></Kumite>
        <Campeonatos></Campeonatos>
        <Tecnica></Tecnica>
        <Aplicaciones></Aplicaciones>
        <Aplicacion_Tecnica></Aplicacion_Tecnica>
        <Demo_Libre></Demo_Libre>
    </Cinturonnegrotercerdan>



    <Cinturonnegrocuartodan>
        <Kumite></Kumite>
        <Kata></Kata>
        <Aplicacion_Tecnica></Aplicacion_Tecnica>
        <Teoria></Teoria>
        <Demo_Libre></Demo_Libre>
    </Cinturonnegrocuartodan>



    <Resultados>
        <Id_Aspirante></Id_Aspirante>
    </Resultados>

</Examen>
